language: python
python:
  - "3.6"
  - "3.7"
services:
  - redis-server
before_install:
  - pip install pycodestyle codecov
  - python setup.py install
script:
  - pycodestyle --exclude=venv --ignore=E501 .
  - coverage run --parallel-mode --branch --source=. -m pytest
  - coverage run --parallel-mode --branch --source=./clients/. -m pytest
  - coverage combine
after_success:
  - codecov

